// v3 验证：重载、开始、跟随+侧面截图，检查重塑后的鹈鹕
const PORT = 9333;
const tabs = await (await fetch(`http://127.0.0.1:${PORT}/json/list`)).json();
const page = tabs.find(t => t.type === 'page');
const ws = new WebSocket(page.webSocketDebuggerUrl);
let id = 0; const pending = new Map();
const send = (m, p = {}) => new Promise((res, rej) => { const i = ++id; pending.set(i, { res, rej }); ws.send(JSON.stringify({ id: i, method: m, params: p })); });
const errors = [];
await new Promise(r => ws.onopen = r);
ws.onmessage = ev => { const d = JSON.parse(ev.data); if (d.id && pending.has(d.id)) { const { res, rej } = pending.get(d.id); pending.delete(d.id); d.error ? rej(new Error(JSON.stringify(d.error))) : res(d.result); return; } if (d.method === 'Runtime.exceptionThrown') errors.push(d.params.exceptionDetails?.text); if (d.method === 'Log.entryAdded' && d.params.entry.level === 'error') errors.push(d.params.entry.text); };
await send('Runtime.enable'); await send('Log.enable'); await send('Page.enable');
const fs = await import('fs');
const OUT = '/home/hatch/workspace/tihu-pelican-3d/verify/';
await send('Page.navigate', { url: 'file:///home/hatch/workspace/tihu-pelican-3d/dist/index.html' });
await new Promise(r => setTimeout(r, 9000));
let r = await send('Runtime.evaluate', { expression: `(() => { const b=document.querySelector('div.go'); const r=b.getBoundingClientRect(); return JSON.stringify({x:r.x+r.width/2,y:r.y+r.height/2}); })()`, returnByValue: true });
const pt = JSON.parse(r.result.value);
await send('Input.dispatchMouseEvent', { type: 'mousePressed', x: pt.x, y: pt.y, button: 'left', clickCount: 1 });
await send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: pt.x, y: pt.y, button: 'left', clickCount: 1 });
await send('Input.dispatchKeyEvent', { type: 'rawKeyDown', code: 'KeyW', key: 'w', windowsVirtualKeyCode: 87 });
await new Promise(r => setTimeout(r, 6000));
await send('Input.dispatchKeyEvent', { type: 'keyUp', code: 'KeyW', key: 'w', windowsVirtualKeyCode: 87 });
let shot = await send('Page.captureScreenshot', { format: 'png' });
fs.writeFileSync(OUT + 'v3-follow.png', Buffer.from(shot.data, 'base64'));
await send('Input.dispatchKeyEvent', { type: 'keyDown', code: 'KeyC', key: 'c', windowsVirtualKeyCode: 67 });
await send('Input.dispatchKeyEvent', { type: 'keyUp', code: 'KeyC', key: 'c', windowsVirtualKeyCode: 67 });
await new Promise(r => setTimeout(r, 2500));
shot = await send('Page.captureScreenshot', { format: 'png' });
fs.writeFileSync(OUT + 'v3-side.png', Buffer.from(shot.data, 'base64'));
console.log('ERRORS:', errors.length, errors.slice(0,5));
ws.close(); process.exit(0);
